### ISSUE TITLE
Term "Context" vs "Team"

### ISSUE THREAD

**Issue by saerdnaer** [public-value-tech/rpoc#1]
```yaml
  Context:
    is_a: NamedThing
    description: >-
      A team, group, project, or other entity that has a context for a person
    class_uri: schema:Project
    mixins:
      - HasAliases
    slots:
      - primary_email
      - mission_statement
      - start_date
      - end_date
      - parent
```
